In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


We group $N$ samples of $k$ random variables on a $k\times N$ data matrix $\mathbf{X}$. Recenter it around a $k\times N$ mean matrix $(\mathbf{\mu})_{ij} = \overline{X_i}$ so that $\mathbf{X'}=\mathbf{X}-\mathbf{\mu}$

The covariance matrix can be calculated as $\dfrac{\mathbf{X'}\cdot\mathbf{X'}^T}{N-1}$

It is $k\times k$ and we wish to diagonalize it to

In [24]:
#Generate data
N = 1000
x1 = np.random.normal(0, 1, size=(1, N)) #N samples from N(0,1) in a column vector
x2 = np.random.normal(0, 3, size=(1, N)) + x1
x3 = 2*x1 + x2
X = np.concatenate((x1, x2, x3), axis=0)

#Compute covariance
#print(np.cov(X))
muX = np.mean(X, axis=1).reshape(3,1)
W = X - muX
cov = W.dot(W.T)/(N-1)

#Compute eigendec.
l, V = la.eig(cov)
print(np.real_if_close(l)) #eigenvalues

#Compute SVD

[[-0.11628994 -0.81649658  0.56551745]
 [-0.57632465 -0.40824829 -0.70794296]
 [-0.80890454  0.40824829  0.42309193]]


2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates.

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset

In [ ]:
# get the dataset and its description on the proper data directory
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P ~/data/
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P ~/data/